name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: yarn global add @0y0/gitbook-cli
      - run: gitbook build .
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.github_token}}
          publish_dir: ./_book
